import = [
  "~/.config/alacritty/vscode-dark.toml",
  # "~/.config/alacritty/vscode-light.toml",
]

shell = "/opt/homebrew/bin/fish"

[font]
size = 14.0

[font.normal]
family = "Berkeley Mono"

[window]
opacity = 0.999

[window.padding]
x = 5

[keyboard]
bindings = [
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true
