shell = "/opt/homebrew/bin/fish"

[font]
size = 14.0

[font.normal]
family = "Berkeley Mono"

[window]
opacity = 0.999

[window.padding]
x = 10

[keyboard]
bindings = [
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
]

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = '#666666'
blue = '#3b8eea'
cyan = '#29b8db'
green = '#23d18b'
magenta = '#d670d6'
red = '#f14c4c'
white = '#e5e5e5'
yellow = '#f5f543'

[colors.cursor]
cursor = '#ffffff'
text = '#000000'

[colors.normal]
black = '#000000'
blue = '#2472c8'
cyan = '#11a8cd'
green = '#0dbc79'
magenta = '#bc3fbc'
red = '#cd3131'
white = '#e5e5e5'
yellow = '#e5e510'

[colors.primary]
background = '#1e1e1e'
foreground = '#cccccc'

[colors.selection]
background = '#3a3d41'
text = '#e0e0e0'
