shell = "/opt/homebrew/bin/fish"

[font]
size = 14.0

[font.normal]
family = "Berkeley Mono"

[window.padding]
x = 10

# Name: VS Code Dark+
[colors.primary]
background = "#1E1E1E"
foreground = "#D4D4D4"

[colors.cursor]
text = "#1d1f21"
cursor = "#cccccc"

[colors.normal]
black = "#000000"
red = "#cd3131"
green = "#0dbc79"
yellow = "#e5e510"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#11a8cd"
white = "#e5e5e5"

[colors.bright]
black = "#666666"
red = "#f14c4c"
green = "#23d18b"
yellow = "#f5f543"
blue = "#3b8eea"
magenta = "#d670d6"
cyan = "#29b8db"
white = "#e5e5e5"
