onboarding = false

[theme]
name = "terminal"

# Flexoki Light
[theme.custom]
accent = "#24837B"
panel_bg = "#FFFCF0"
sidebar_bg = "#F2F0E5"
active_row_bg = "#E6E4D9"
selection_bg = "#DAD8CE"
surface0 = "#E6E4D9"
surface1 = "#CECDC3"
surface_dim = "#E6E4D9"
overlay0 = "#6F6E69"
overlay1 = "#6F6E69"
text = "#100F0F"
subtext0 = "#6F6E69"
mauve = "#5E409D"
green = "#66800B"
yellow = "#AD8301"
red = "#AF3029"
blue = "#205EA6"
teal = "#24837B"
peach = "#BC5215"

[keys]
switch_tab = "cmd+1..9"
new_tab = "cmd+t"
new_workspace = "cmd+n"
new_worktree = "cmd+shift+n"
split_vertical = "cmd+d"
goto = "cmd+/"

[ui]
prompt_new_tab_name = false

[ui.sidebar.spaces]
row_gap = 1

[ui.toast.clipboard]
position = "top-right"
