onboarding = false

[theme]
auto_switch = true
dark_name = "rose-pine"
light_name = "rose-pine-dawn"

[ui]
prompt_new_tab_name = false

[ui.sidebar.spaces]
row_gap = 1

[ui.toast.clipboard]
position = "top-right"
