# change index start
set -g base-index 1

# title
set-window-option -g automatic-rename on
set-option -g set-titles on

# switch pane with alt+arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch window with shift+arrow
bind -n S-Left  previous-window
bind -n S-Right next-window

# esc delay
set -sg escape-time 0

# color issue
set-option -ga terminal-overrides ",*256col*:Tc"

# statusline color
set -g window-status-current-style "bg=yellow,bold"

# reload config
bind r source-file ~/.tmux.conf
