# index
set -g base-index 1

# color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# status bar
setw -g window-status-current-style bg=black,fg=green

# escape no delay
set -sg escape-time 0

# reload configuration
bind r source-file ~/.tmux.conf

# pane navigation
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# window navigation
bind -n S-Left  previous-window
bind -n S-Right next-window

# split navigation
bind-key v split-window -h
bind-key s split-window -v
