unbind C-b
set-option -g prefix `
bind ` send-prefix

set -g base-index 1
set -g escape-time 0
set -g status-position top
set -g status-left-length 0
set -g status-style bg=white,fg=black
set -g window-status-current-style bg=black,fg=white

set -g @plugin 'tmux-plugin/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
