[bootstrap.packages]
"brew-cask:rar" = "latest"
"brew-cask:1password" = "latest"
"brew-cask:caffeine" = "latest"
"brew-cask:chatgpt" = "latest"
"brew-cask:helium-browser" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:openvpn-connect" = "latest"

[bootstrap.macos.defaults."com.apple.dock"]
autohide = true
launchanim = false
mineffect = "scale"
"minimize-to-application" = true
"mru-spaces" = false
orientation = "left"
"show-recents" = false
tilesize = 32
"workspaces-auto-swoosh" = false

[bootstrap.macos.defaults."com.apple.AppleMultitouchTrackpad"]
Clicking = true
TrackpadRightClick = true
TrackpadThreeFingerDrag = true

[bootstrap.macos.defaults.NSGlobalDomain]
KeyRepeat = 2
InitialKeyRepeat = 15
ApplePressAndHoldEnabled = false
AppleShowAllExtensions = true

[bootstrap.macos.defaults."com.apple.menuextra.battery"]
ShowPercent = "YES"

[bootstrap.macos.defaults."com.apple.Spotlight"]
MenuItemHidden = true

[bootstrap.macos.defaults."com.apple.finder"]
AppleShowAllFiles = true
ShowPathbar = true
ShowStatusBar = true
FXPreferredViewStyle = "Nlsv"
FXDefaultSearchScope = "SCcf"
FXEnableExtensionChangeWarning = false
NewWindowTarget = "PfHm"

[bootstrap.hooks.post-defaults]
run = [
  '''test -f /etc/pam.d/sudo_local || sudo cp /etc/pam.d/sudo_local.template /etc/pam.d/sudo_local; sudo sed -i '' 's/^#auth[[:space:]]*sufficient[[:space:]]*pam_tid\.so/auth       sufficient     pam_tid.so/' /etc/pam.d/sudo_local''',
  "defaults write com.apple.dock persistent-apps -array",
  "killall Dock Finder SystemUIServer 2>/dev/null || true",
]

[bootstrap.hooks.final]
run = "cp ~/.dotfiles/fonts/*.otf ~/Library/Fonts/"

[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"
