# prefix
unbind C-b
set-option -g prefix `
bind ` send-prefix

# easier split and window
bind c new-window      -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# basic configuration
set -g aggressive-resize on
set -g base-index 1
set -g default-command "${SHELL}"
set -g default-terminal "screen-256color"
set -g escape-time 0
set -g mouse on
set -g renumber-windows on
set -sa terminal-overrides ",alacritty:RGB"

# statusline
set -g status-interval 1
set -g status-position top
set -g status-left-length 0
set -g status-right-length 0

set -g status-style "fg=white,bg=black"
set -g status-left-style "fg=black,bg=brightblue"
set -g status-right-style "fg=white,bg=brightblack,bold"

set -g status-left " #S "
set -g status-right " #(/bin/bash ${HOME}/.tmux/plugins/kube-tmux/kube.tmux white red cyan) "

set -g window-status-separator ""
set -g window-status-current-format "#{?window_zoomed_flag,#[bg=yellow] #I #W , #I #W }"
set -g window-status-current-style "fg=black,bg=brightcyan"
set -g window-status-format " #I #W "

# plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'jonmosco/kube-tmux'

set -g @continuum-restore 'on'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'
run '~/.tmux/plugins/tpm/tpm'

