# prefix
unbind C-b
set-option -g prefix `
bind ` send-prefix

# easier split and window
bind c new-window      -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# basic configuration
set -g base-index 1
set -g default-terminal "screen-256color"
set -g escape-time 0
set -g mouse on
set -g renumber-windows on
set -g status-left-length 0
set -g status-right-length 0
set -g status-position top
set -sa terminal-overrides ",alacritty:RGB"

# vim-tmux navigation
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'M-Left'	if-shell "$is_vim" 'send-keys C-h'		'select-pane -L'
bind-key -n 'M-Down'	if-shell "$is_vim" 'send-keys C-j'		'select-pane -D'
bind-key -n 'M-Up'		if-shell "$is_vim" 'send-keys C-k'		'select-pane -U'
bind-key -n 'M-Right'	if-shell "$is_vim" 'send-keys C-l'		'select-pane -R'

bind-key -T copy-mode-vi 'M-Left'	select-pane -L
bind-key -T copy-mode-vi 'M-Down'	select-pane -D
bind-key -T copy-mode-vi 'M-Up'		select-pane -U
bind-key -T copy-mode-vi 'M-Right'	select-pane -R

# plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'arcticicestudio/nord-tmux'
set -g @plugin 'jonmosco/kube-tmux'

set -g @continuum-restore 'on'
set -g @nord_tmux_no_patched_font "1"

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'
run '~/.tmux/plugins/tpm/tpm'

set -ga status-right "#[bg=brightblack] #(/bin/bash ${HOME}/.tmux/plugins/kube-tmux/kube.tmux black red cyan) "
