[settings]

[settings.npm]
package_manager = "bun"

[tools]
buf = "latest"
bun = "latest"
codex = "latest"
difftastic = "latest"
elixir = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
jq = "latest"
jujutsu = "latest"
kubectl = "latest"
node = "latest"
rg = "latest"
rust = "latest"
sd = "latest"
shellcheck = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
"cargo:lisette" = "latest"
"github:AlexanderGrooff/mermaid-ascii" = "latest"
"github:git-town/git-town" = "latest"
"github:jsdelivr/globalping-cli" = "latest"
"github:lance0/ttl" = "latest"
"github:psviderski/uncloud" = "latest"
"github:sarub0b0/kubetui" = "latest"
"github:usagi-flow/evil-helix" = "latest"
"go:github.com/almonk/bontree" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:agent-browser" = "latest"
"npm:cf" = "latest"
"npm:local-leetcode-trainer" = "latest"
"pipx:mycli" = "latest"
"pipx:pgcli" = "latest"
